# Pandas Basics: Data Analysis Toolkit

**Duration:** 3 Hours  
**Format:** Interactive Zoom Session

## 📋 Pre-Class Setup
Please run the cell below to ensure your environment is ready. We will use `numpy` and `pandas` throughout this lesson.

In [4]:
import pandas as pd
import numpy as np

print("Pandas version:", pd.__version__)
print("Numpy version:", np.__version__)

Pandas version: 1.5.3
Numpy version: 1.26.4

---

## 🎯 Section 1: Creating & Modifying Data Structures (60 min)

### Learning Objectives (LO1)
By the end of this section, you will be able to:
- **Create** Series and DataFrames from raw data.
- **Modify** DataFrames by adding new columns and changing values.
- **Identify** the index and column components.
- **Detect** missing values using `isna()` and `notna()`.

### 📖 Concept: The Series
A Series is a one-dimensional array with labeled indices. It's the building block of a DataFrame.

In [3]:
# [DEMO] Creating a Series
obj = pd.Series([4, 7, -5, 3], index=["d", "b", "a", "c"])
print(obj)
obj['a']

d    4
b    7
a   -5
c    3
dtype: int64

-5

### 📖 Concept: The DataFrame
A DataFrame is a 2-dimensional labeled data structure. Think of it as a dictionary of Series objects (each column is a Series).

In [5]:
# [DEMO] Creating a DataFrame from a dictionary
data = {
    "state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
    "year": [2000, 2001, 2002, 2001, 2002, 2003],
    "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
}

frame = pd.DataFrame(data)
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [6]:
frame.head(2)

  state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7

### 👨‍🏫 Instructor Demo: Inspecting & Modifying
1. `head()` and `tail()`
2. Accessing columns (dictionary syntax vs dot syntax)
3. Adding a new column

In [9]:
# [DEMO] Inspecting data
print("First 5 rows:")
display(frame.head())

# [DEMO] Accessing a column
print("Population column:")
display(frame['pop'])

First 5 rows:

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

Population column:

0    1.5
1    1.7
2    3.6
3    2.4
4    2.9
5    3.2
Name: pop, dtype: float64

In [10]:
# [DEMO] Adding a new column with a scalar value
frame['debt'] = 16.5
frame

    state  year  pop  debt
0    Ohio  2000  1.5  16.5
1    Ohio  2001  1.7  16.5
2    Ohio  2002  3.6  16.5
3  Nevada  2001  2.4  16.5
4  Nevada  2002  2.9  16.5
5  Nevada  2003  3.2  16.5

In [12]:
# [DEMO] Adding a calculated column
frame['eastern'] = (frame.state == 'Ohio')  
#frame['eastern'] = (frame['state'] == 'Ohio')   # alt
frame

    state  year  pop  debt  eastern
0    Ohio  2000  1.5  16.5     True
1    Ohio  2001  1.7  16.5     True
2    Ohio  2002  3.6  16.5     True
3  Nevada  2001  2.4  16.5    False
4  Nevada  2002  2.9  16.5    False
5  Nevada  2003  3.2  16.5    False

### 📖 Concept: Detecting Missing Data
Real-world data often has missing values (shown as `NaN`). Use `isna()` and `notna()` to detect them.

In [29]:
# [DEMO] Detecting missing values
data_with_nan = pd.Series([1, np.nan, 3.5, np.nan, 7])   #nan: not a number

print("Original data:")
display(data_with_nan)

print("Which values are missing? isna()")
print(data_with_nan.isna())
print("Count of missing values:", sum(data_with_nan.isna()))

print("\nWhich values are NOT missing? notna()")
display(data_with_nan.notna())

Original data:

0    1.0
1    NaN
2    3.5
3    NaN
4    7.0
dtype: float64

Which values are missing? isna()
0    False
1     True
2    False
3     True
4    False
dtype: bool
Count of missing values: 2

Which values are NOT missing? notna()

0     True
1    False
2     True
3    False
4     True
dtype: bool

### ✏️ Hands-On Activity: The Inventory System

**Scenario:** You manage a small grocery store. You need to track your fruit inventory.

**Tasks:**
1. Create a DataFrame named `inventory` from the provided dictionary `fruit_data`.
2. Add a new column `price` with values `[3.0, 4.0, 2.0, 5.0]`.
3. Add a column `total_value` which is `quantity * price`.
4. Create a boolean column `low_stock` that is `True` if quantity is less than 50.

In [20]:
# [EXERCISE] Starter Code
fruit_data = {
    "fruit": ["Apple", "Banana", "Cherry", "Date"],
    "quantity": [100, 40, 200, 20]
}

# 1. Create DataFrame
inventory = pd.DataFrame(fruit_data)

# 2. Add Price
inventory['price'] = [3., 4., 2., 5.]

# 3. Calculate Total Value
inventory['total_value'] = inventory['quantity'] * inventory['price']

# 4. Flag Low Stock
inventory['low_stock'] = inventory['quantity'] < 50

# Display result
inventory

    fruit  quantity  price  total_value  low_stock
0   Apple       100    3.0        300.0      False
1  Banana        40    4.0        160.0       True
2  Cherry       200    2.0        400.0      False
3    Date        20    5.0        100.0       True

---

## 🎯 Section 2: Indexing and Selection (60 min)

### Learning Objectives (LO2)
By the end of this section, you will be able to:
- **Differentiate** between label-based (`loc`) and position-based (`iloc`) indexing.
- **Apply** boolean filtering to select specific rows.
- **Drop** rows or columns from a DataFrame.
- **Modify** specific data points using selection.

In [48]:
# Setup for Demo
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [26]:
data.loc["Colorado"]

# data.loc[["Colorado"]]  # tabular

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

### 👨‍🏫 Instructor Demo: Loc vs Iloc
- **.loc[row_label, col_label]**: "Address" based.
- **.iloc[row_pos, col_pos]**: "GPS" based (integers).

In [28]:
# [DEMO] Select 'Colorado' row using loc
print("--- Row by Label ---")
display(data.loc["Colorado"])

# [DEMO] Select 'Colorado' row using iloc (it's at index 1)
print("\n--- Row by Position ---")
display(data.iloc[1])   # tabular: iloc[[1]]

--- Row by Label ---

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

--- Row by Position ---

one      4
two      5
three    6
four     7
Name: Colorado, dtype: int64

In [ ]:
# [DEMO] Boolean Filtering
# Return rows where column 'three' is greater than 5
data[data["three"] > 5]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

### 📖 Concept: Dropping Rows and Columns
Use the `drop()` method to remove rows or columns. By default, it drops rows. Use `axis=1` or `axis="columns"` to drop columns.

In [ ]:
# [DEMO] Dropping rows and columns
# Drop rows (default axis=0)
print("Drop rows 'Colorado' and 'Ohio':")
display(data.drop(["Colorado", "Ohio"]))    #default axis=0 (row)

print("\nDrop column 'two':")
display(data.drop("two", axis=1))

#data.drop(["Colorado", "Ohio"], inplace=True)

Drop rows 'Colorado' and 'Ohio':

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

Drop column 'two':

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

### ✏️ Hands-On Activity: Data Detective

**Tasks:**
Using the `data` DataFrame provided above:
1. Select the rows for 'Utah' and 'New York' only.
2. Select the value in the 'two' column for 'Ohio' (should be 1).
3. Select all rows where column 'three' is greater than 5.
4. Update the value of 'four' in the 'New York' row to be 100.

In [52]:
# 1. rows for Utah and New York
display(data.loc[['Utah', 'New York']])

# 2. value in column 'two' for 'Ohio'
display(data.iloc[0,1])     

# 3. Filter col 'three' > 5
display(data[data.three>5])

# 4. Update value
data.loc['New York', 'four']=888
data

# select multiple row & col
print(data.loc[['Ohio', 'New York'], ['two', 'four']])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14   888

1

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14   888

          two  four
Ohio        1     3
New York   13   888

---

## 🎯 Section 3: Function Application, Sorting, & Ranking (60 min)

### Learning Objectives (LO3 & LO4)
By the end of this section, you will be able to:
- **Sort** data by index or values.
- **Rank** data to handle ties.
- **Apply** custom functions to transform data.

In [67]:
# Setup Data
frame = pd.DataFrame({
    "b": [4, 7, -3, 2], 
    "a": [0, 1, 0, 1]
}, index=['Row1', 'Row2', 'Row3', 'Row4'])
frame

      b  a
Row1  4  0
Row2  7  1
Row3 -3  0
Row4  2  1

### 👨‍🏫 Instructor Demo: Sorting & Ranking
1. `sort_index()`
2. `sort_values(by=...)`
3. `rank()`

In [69]:
# [DEMO] Sort by values in column 'b'
frame.sort_values(by="b")                  # default ascending
#frame.sort_values("b", ascending=False)     # descending

      b  a
Row3 -3  0
Row4  2  1
Row1  4  0
Row2  7  1

In [ ]:
# [DEMO] Applying a function .apply(fn) (avoid for loop! for is slow)
def label_size(val):
    return "Big" if val > 2 else "Small"

frame['b_size'] = frame['b'].apply(label_size)
frame

      b  a b_size
Row1  4  0    Big
Row2  7  1    Big
Row3 -3  0  Small
Row4  2  1  Small

### ✏️ Hands-On Activity: Leaderboard Logic

**Scenario:** You have exam scores. You need to rank them and assign a Pass/Fail status.

**Tasks:**
1. Run the starter code to generate the `scores` DataFrame.
2. Sort the DataFrame by 'Math' score in descending order (highest first).
3. Create a new column 'Math_Rank' using the `.rank()` method.
4. Define a function that returns "Pass" if score >= 60 and "Fail" otherwise.
5. Apply this function to the 'Math' column to create a new 'Status' column.

In [102]:
# [EXERCISE] Starter Code
scores = pd.DataFrame({
    "Student": ["Alice", "Bob", "Charlie", "David"],
    "Math": [85, 45, 92, 60],
    "Science": [70, 55, 88, 72]
})
scores

   Student  Math  Science
0    Alice    85       70
1      Bob    45       55
2  Charlie    92       88
3    David    60       72

In [ ]:
# 2. sort Math scores in desc
print(scores.sort_values('Math', ascending=False))
# scores.sort_values('Math', ascending=False, inplace=True)  # to replace df

# 3. create new Math_rank column, highest score rank 1
scores['Math_rank'] = scores['Math'].rank(ascending=False) 
print(scores)

#4. define fn; 5. apply fn to Math
def Pass_Fail(score):
    return 'Pass' if score>60 else 'Fail'

scores['Math_status'] = scores['Math'].apply(Pass_Fail)
scores

   Student  Math  Science
2  Charlie    92       88
0    Alice    85       70
3    David    60       72
1      Bob    45       55
   Student  Math  Science  Math_rank
0    Alice    85       70        2.0
1      Bob    45       55        4.0
2  Charlie    92       88        1.0
3    David    60       72        3.0

   Student  Math  Science  Math_rank Math_status
0    Alice    85       70        2.0        Pass
1      Bob    45       55        4.0        Fail
2  Charlie    92       88        1.0        Pass
3    David    60       72        3.0        Fail

In [96]:
scores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Student      4 non-null      object
 1   Math         4 non-null      int64
 2   Science      4 non-null      int64
 3   Math_rank    4 non-null      float64
 4   Math_status  4 non-null      object
dtypes: float64(1), int64(2), object(2)
memory usage: 288.0+ bytes

## 🎓 Lesson Summary

1. **Data Structures:** Series (1D) and DataFrame (2D) are the building blocks.
2. **Missing Data:** Use `isna()` and `notna()` to detect missing values.
3. **Selection:** Use `.loc[]` for labels and `.iloc[]` for positions. Use `.drop()` to remove rows/columns.
4. **Operations:** Vectorized operations are faster than loops. Use `.apply()` for custom logic.
5. **Sorting:** Organize your data to find insights quickly.

**Next Steps:** In the next lesson, we will cover Data Cleaning (handling missing values) and Aggregation (GroupBy).

### Post-class

In [ ]:
# Not executable, just answers to questions
# Q1: Select all numeric columns except float from the DataFrame dft.
dft.select_dtypes(include=['number'], exclude=['float'])

# Q2: How do you return the last 3 rows of a DataFrame df?
df.tail(3)

# Q3: Return the minimum and maximum of a Series x as a new Series with the index ["min", "max"].
pd.Series([x.min(), x.max()], index=["min", "max"])

# Q4: Multiply df1 and df2 (two DataFrames) with a fill_value of 1.
df1.multiply(df2, fill_value=1)

In [ ]:
# Q5: How do you create a DataFrame from a nested dictionary of dictionaries?
nested_dict = {'A': {'a': 1, 'b': 2}, 'B': {'a': 3, 'b': 4}}
df = pd.DataFrame(nested_dict).T
df

   a  b
A  1  2
B  3  4

In [ ]:
# Series Reindexing
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
print("Original Series:")
print(obj)

# Reindex with new labels
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])
print("\nReindexed Series:")
print(obj2)

Original Series:
d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

Reindexed Series:
a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [35]:
# Dataframe Reindexing
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
display(frame)

# Reindex rows
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
print("Reindexed Rows:")
print(frame2)

# Reindex columns
states = ["Texas", "Utah", "California"]
print("\nReindexed Columns:")
print(frame.reindex(columns=states))

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

Reindexed Rows:
   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

Reindexed Columns:
   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [ ]:
# Interpolation
# fill missing values with last known value (forward fill) - useful for time series data
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
print(obj3)
print(obj3.reindex(np.arange(6), method="ffill"))

0      blue
2    purple
4    yellow
dtype: object
0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [ ]:
# With DataFrame, index values can be deleted from either axis.
# Dropping from DF
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=["Ohio", "Colorado", "Utah", "New York"],
                    columns=["one", "two", "three", "four"])
print(data)

# Drop rows (default axis=0)
print(data.drop(["Colorado", "Ohio"]))

# Drop columns (axis=1 or axis="columns")
print(data.drop("two", axis=1))

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15
          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [ ]:
# Data Alignment --- When adding two DataFrames, 
# if index pairs are not the same, the respective index in the result will be the union of the index pairs
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),
                   index=["Ohio", "Texas", "Colorado"])

df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),
                   index=["Utah", "Ohio", "Texas", "Oregon"])

# Adding them results in NaNs where labels don't overlap
print(df1)
print(df2)
print(df1 + df2)

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0
          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0
            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [ ]:
# Filling Values --- fill missing values with a special value
# when an axis label is found in one object but not the other using .add method
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list("abcd"))
print(df1)
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list("abcde"))
df2.loc[1, "b"] = np.nan
print(df2)

# Add with fill_value=0 --> substitutes 0 for any missing values / NaN
print(df1.add(df2, fill_value=888888))

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0
          a         b         c         d         e
0       0.0       2.0       4.0       6.0  888892.0
1       9.0  888893.0      13.0      15.0  888897.0
2      18.0      20.0      22.0      24.0  888902.0
3  888903.0  888904.0  888905.0  888906.0  888907.0

In [ ]:
'''
Combining Overlapping Data
combine two datasets where values in one are preferred over the other,
combine_first allows you to patch missing data in one object with data from another.
'''

df1 = pd.DataFrame({
    "A": [1.0, np.nan, 3.0, 5.0, np.nan],
    "B": [np.nan, 2.0, 3.0, np.nan, 6.0]
})

df2 = pd.DataFrame({
    "A": [5.0, 2.0, 4.0, np.nan, 3.0, 7.0],
    "B": [np.nan, np.nan, 3.0, 4.0, 6.0, 8.0],
})

# Patch missing values in df1 with values from df2
print(df1)
print(df2)
print(df1.combine_first(df2))

     A    B
0  1.0  NaN
1  NaN  2.0
2  3.0  3.0
3  5.0  NaN
4  NaN  6.0
     A    B
0  5.0  NaN
1  2.0  NaN
2  4.0  3.0
3  NaN  4.0
4  3.0  6.0
5  7.0  8.0
     A    B
0  1.0  NaN
1  2.0  2.0
2  3.0  3.0
3  5.0  4.0
4  3.0  6.0
5  7.0  8.0